### ISSUE TITLE
Date error, what is the proper format?

### ISSUE THREAD

**Issue by rotyflo** [GermanSumus/Calendar#1]
![screenshot from 2019-01-22 00-12-21](https://user-images.githubusercontent.com/17039418/51515745-7ab0e480-1dda-11e9-804b-a2c6d97fad2a.png)

**Comment by GermanSumus** [comment]
Bug in sanitation.py. The day has to be after today’s day date. 1/22/19. If day is > today valid, else wrong.

**Comment by rotyflo** [comment]
![screenshot from 2019-01-22 00-18-46](https://user-images.githubusercontent.com/17039418/51515989-50135b80-1ddb-11e9-9093-1c5ba9db40ed.png)

**Comment by rotyflo** [comment]
Ahhh I think I see, it is bugging out because of the DAY specifically

I get it

So it returns an error with 2019-02-06 because 06 < current day (21)

I got it to accept 2019-02-22, but then it asks for the date again and returns the date + 00:00:00

**Comment by GermanSumus** [comment]
Yeah it’s a hassle trying to sanitize the input to a valid date. I’m still looking for a way to make it work. Might work on it in the morning actually

**Comment by rotyflo** [comment]
target_year must be >= current_year

        if target_year == current_year
            target_month must be >= current_month

            if target_year == current_year and target_month == current_month
                target_day must be >= current_day
